services:
  parser:
    image: shivan2418/main_repo:iparser
    volumes:
    - ./output:/app/output
    - ./input:/app/input
    command: /bin/bash -c "python3 ingredient_phrase_tagger/processing/parse_ingredients.py"
